version: '3'

# Перечень volume
volumes:
  pg_data_production:
  static_volume:
  media_volume:

# Перечень контейнеров
services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data
  backend:
    image: ${USERNAME}/foodgram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
      - media_volume:/media/
    depends_on:
      - db
  frontend:
    image: ${USERNAME}/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
  gateway:
    image: ${USERNAME}/foodgram_gateway
    env_file: .env
    volumes:
      - ./docs/:/usr/share/nginx/html/api/docs/
      - static_volume:/staticfiles/
      - media_volume:/media/
    ports:
      - ${GATEWAY_PORTS}